### ISSUE TITLE
[Bug]: Please add a ssl certificate to the website it is showing a threat 

### ISSUE THREAD

**Issue by Gitstar-OC** [lorebooks-wiki/mkdocs-hackclub#1]
### About this Issue

![image](https://github.com/user-attachments/assets/dc2c318e-adf3-4d06-b3e3-32f4c2ae7203)

### Environment details

For theme users:
* Python and OS version:
* Theme version on PyPi or Git commit hash:
* Link to your docs repo for reproducibility (optional):

For visitors:
* Browser name and version:
* OS version:

**Comment by ajhalili2006** [comment]
I probably forgot to enable HTTPS, lemme flip the switch.

**Comment by ajhalili2006** [comment]
Apologies for the delay and inconvenience, but I successfully readded the domain to update the TLS certificates. Now closing this issue.
